### PR TITLE
Add fr-FR

### PR DESCRIPTION
**Pull request by FJduFou**
I translate after

### CODE REVIEW

**Comment by ikarago** [comment]
Will look into this when I'm home so I can properly merge the different PR's together. :) 

Thank you so much so far for the help with translating the app! 😊

**Comment by ikarago** [comment]
It has been added. Again thank you so much for translating the app! 😊

**Comment by ikarago** [comment]
@FJduFou Hmmm, seems like the resource file for FR-fr still only contains the English strings.

Do you happen to have a file with the raw translations still with you? If so, can you send them to me, then I'll add them manually. ;)

**Comment by FJduFou** [comment]
image

**Comment by FJduFou** [comment]
I preferred to do it in 2 steps,
the 1st was the integration of Language Toolkit (refuse)
the 2nd was the translation (in progress)

**Comment by ikarago** [comment]
All right, feel free to do a PR with all the changes in it when it's ready. :) That way the PR will include all changes you've made (as multiple seperate PR's make it crazy hard for me to see which ones have the most current changes. ;) )

**Comment by FJduFou** [comment]
I did not know how to put multiple files in one PR

**Comment by ikarago** [comment]
If you work in your fork you can create commits to your own repo so you can still work incremental. Once you're done, you can click on "New Pull Request" on this repository. GitHub will then automatically select your main branch (you can also select a different one) that you want to merge with my repo.

If you do that the Pull Request will automatically include all changes you've made and synced with your fork on GutHub. 😊

**Comment by FJduFou** [comment]
oki, thx 😅

**Pull request merged**
